CREATE SEQUENCE SQ_NUMCASA
INCREMENT BY 1
START WITH 0000000000001
NOCACHE
NOCYCLE;
     
CREATE SEQUENCE SQ_CUOTA
INCREMENT BY 1
START WITH 0000000000001
NOCACHE
NOCYCLE;
 
------------------------------&------------------------------------------
--SELECTS Y DROPS Y COMMIT

COMMIT;

DROP TABLE CONDOMINIO.DUENOS;
DROP TABLE CONDOMINIO.ACCESOS;
DROP TABLE CONDOMINIO.CUOTAS_CONDOMINALES;
DROP TABLE CONDOMINIO.FILIARES_CONDOMINIOS;
DROP TABLE CONDOMINIO.TIPO_CUOTAS;
DROP TABLE CONDOMINIO.TIPO_DUENO;

     

SELECT * FROM CONDOMINIO.TIPO_DUENO;
SELECT * FROM CONDOMINIO.DUENOS;
SELECT * FROM CONDOMINIO.FILIARES_CONDOMINIOS;
SELECT * FROM CONDOMINIO.TIPO_CUOTAS;
SELECT * FROM  CONDOMINIO.CUOTAS_CONDOMINALES;
SELECT * FROM CONDOMINIO.ACCESOS;
------------------------------&------------------------------------------
---CREAR TABLES
CREATE TABLE CONDOMINIO.DUENOS(
CEDULA VARCHAR2(50) NOT NULL,
NOMBRE VARCHAR2(50) NOT NULL,
APE1 VARCHAR2(50) NOT NULL,
APE2 VARCHAR2(50) NOT NULL,
TELEFONO INT NOT NULL,
EMAIL VARCHAR2(50) NOT NULL,
TIPO VARCHAR2(50) NOT NULL,
CONSTRAINT PK_DUENOS PRIMARY KEY (CEDULA));



CREATE TABLE CONDOMINIO.CUOTAS_CONDOMINALES(
ID_COUTA INT NOT NULL,
NUM_CASA INT NOT NULL,
PRECIO FLOAT NOT NULL,
TIPO VARCHAR2(50) NOT NULL,
CONSTRAINT PK_CUOTAS_CORDOMINALES PRIMARY KEY (ID_COUTA));


CREATE TABLE CONDOMINIO.ACCESOS(
CEDULA VARCHAR2(50) NOT NULL,
NOMBRE VARCHAR(50) NOT NULL,
APE1 VARCHAR(50) NOT NULL,
APE2 VARCHAR2(50) NOT NULL,
NUM_CASA INT NOT NULL,
DESCRIPCION VARCHAR2(50) NOT NULL,
FECHA VARCHAR2(50) NOT NULL,
CONSTRAINT PK_ACCESOS PRIMARY KEY (CEDULA));


CREATE TABLE CONDOMINIO.FILIARES_CONDOMINIOS(
NUM_CASA INT NOT NULL,
CEDULA_DUENO VARCHAR(50) NOT NULL,
CONSTRAINT PK_FILIARES_CONDOMINIOS PRIMARY KEY (NUM_CASA));


CREATE TABLE CONDOMINIO.TIPO_CUOTAS(
TIPO VARCHAR2(50) NOT NULL,
DESCRIPCION VARCHAR2(50) NOT NULL,
CONSTRAINT PK_TIPO_CUOTAS PRIMARY KEY (TIPO));

CREATE TABLE CONDOMINIO.TIPO_DUENO(
TIPO VARCHAR2(50) NOT NULL,
DESCRIPCION VARCHAR2(50) NOT NULL,
CONSTRAINT PK_TIPO_DUENO PRIMARY KEY (TIPO));
 
 

------------------------------&------------------------------------------
ALTER TABLE CONDOMINIO.FILIARES_CONDOMINIOS ADD CONSTRAINT FK_DUENOS
FOREIGN KEY (CEDULA_DUENO)
REFERENCES CONDOMINIO.DUENOS(CEDULA);

ALTER TABLE CONDOMINIO.ACCESOS ADD CONSTRAINT FK_FILIARES
FOREIGN KEY (NUM_CASA)
REFERENCES CONDOMINIO.FILIARES_CONDOMINIOS(NUM_CASA);

ALTER TABLE CONDOMINIO.CUOTAS_CONDOMINALES ADD CONSTRAINT FK_CUOTAS
FOREIGN KEY (NUM_CASA)
REFERENCES CONDOMINIO.FILIARES_CONDOMINIOS(NUM_CASA);

ALTER TABLE CONDOMINIO.CUOTAS_CONDOMINALES ADD CONSTRAINT FK_CUOTAST
FOREIGN KEY (TIPO)
REFERENCES CONDOMINIO.TIPO_CUOTAS(TIPO);

ALTER TABLE CONDOMINIO.DUENOS ADD CONSTRAINT FK_DUENOST
FOREIGN KEY (TIPO)
REFERENCES CONDOMINIO.TIPO_DUENO(TIPO);






------------------------------TIPO DUENOS------------------------------------------
create or replace NONEDITIONABLE PROCEDURE SP_TP_DUENO(PTIPO IN VARCHAR2,PDESCRIPCION IN VARCHAR2)
IS
BEGIN
    INSERT INTO CONDOMINIO.TIPO_DUENO(TIPO ,DESCRIPCION  )
    VALUES (PTIPO ,PDESCRIPCION);
    EXCEPTION WHEN OTHERS THEN ROLLBACK;
    
END SP_TP_DUENO;
COMMIT;



CREATE OR REPLACE PROCEDURE SP_DEL_TP_DUENO(PTIPO IN VARCHAR2)
IS
BEGIN
    DELETE FROM CONDOMINIO.TIPO_DUENO  WHERE TIPO = PTIPO ;
    EXCEPTION WHEN OTHERS THEN ROLLBACK;
    
END SP_DEL_TP_DUENO;
COMMIT;




CREATE OR REPLACE PROCEDURE SP_UPD_TP_DUENO(PTIPO IN VARCHAR2,PDESCRIPCION IN VARCHAR2)
IS
BEGIN
    UPDATE  CONDOMINIO.TIPO_DUENO SET  DESCRIPCION = PDESCRIPCION WHERE TIPO = PTIPO;
    EXCEPTION WHEN OTHERS THEN ROLLBACK;
    
END  SP_UPD_TP_DUENO;
COMMIT;


------------------------------DUENOS------------------------------------------
create or replace NONEDITIONABLE PROCEDURE SP_DUENO(PCEDULA IN VARCHAR2, PNOMBRE IN VARCHAR2, PAPE1 IN VARCHAR2, PAPE2 IN VARCHAR2 , PTELEFONO IN INT, PEMAIL IN VARCHAR2, PTIPO IN VARCHAR2)
IS
BEGIN
    INSERT INTO CONDOMINIO.DUENOS(CEDULA , NOMBRE , APE1 , APE2  , TELEFONO , EMAIL, TIPO )
    VALUES (PCEDULA, PNOMBRE , PAPE1 , PAPE2 , PTELEFONO , PEMAIL, PTIPO);
    EXCEPTION WHEN OTHERS THEN ROLLBACK;
    
END SP_DUENO;
COMMIT;



CREATE OR REPLACE PROCEDURE SP_DEL_DUENO(PCEDULA IN VARCHAR2)
IS
BEGIN
    DELETE FROM CONDOMINIO.DUENOS  WHERE CEDULA  = PCEDULA ;
    EXCEPTION WHEN OTHERS THEN ROLLBACK;
    
END SP_DEL_DUENO;
COMMIT;

CREATE OR REPLACE PROCEDURE SP_UPD_DUENO(PCEDULA IN VARCHAR2, PNOMBRE IN VARCHAR2, PAPE1 IN VARCHAR2, PAPE2 IN VARCHAR2 , PTELEFONO IN INT, PEMAIL IN VARCHAR2 , PTIPO VARCHAR2)
IS
BEGIN
    UPDATE  CONDOMINIO.DUENOS SET  NOMBRE = PNOMBRE , APE1 = PAPE1 , APE2 = PAPE2, TELEFONO = PTELEFONO, EMAIL = PEMAIL, TIPO = PTIPO WHERE CEDULA = PCEDULA;
    EXCEPTION WHEN OTHERS THEN ROLLBACK;
    
END  SP_UPD_DUENO;
COMMIT;

--------------------------------FILIARES----------------------------------------


create or replace NONEDITIONABLE PROCEDURE SP_FILIARES(PNUM_CASA IN INT, PCEDULA_DUENO IN VARCHAR2)
IS
BEGIN
    INSERT INTO CONDOMINIO.FILIARES_CONDOMINIOS(NUM_CASA , CEDULA_DUENO )
    VALUES (PNUM_CASA , PCEDULA_DUENO);
    EXCEPTION WHEN OTHERS THEN ROLLBACK;
    
END SP_FILIARES;
COMMIT;


CREATE OR REPLACE PROCEDURE SP_DEL_FILIARES(PNUM_CASA IN INT)
IS
BEGIN
    DELETE FROM CONDOMINIO.FILIARES_CONDOMINIOS  WHERE NUM_CASA  = PNUM_CASA ;
    EXCEPTION WHEN OTHERS THEN ROLLBACK;
   
END SP_DEL_FILIARES;
COMMIT;




CREATE OR REPLACE PROCEDURE SP_UPD_FILIARES( PNUM_CASA IN INT, PCEDULA_DUENO IN VARCHAR2)
IS
BEGIN
    UPDATE  CONDOMINIO.FILIARES_CONDOMINIOS SET CEDULA_DUENO = PCEDULA_DUENO WHERE NUM_CASA = PNUM_CASA;
    EXCEPTION WHEN OTHERS THEN ROLLBACK;
    
END  SP_UPD_FILIARES;
COMMIT;



------------------------------TIPO CUOTA------------------------------------------
create or replace NONEDITIONABLE PROCEDURE SP_TP_CUOTA(PTIPO IN VARCHAR2,PDESCRIPCION IN VARCHAR2)
IS
BEGIN                                        
    INSERT INTO CONDOMINIO.TIPO_CUOTAS(TIPO ,DESCRIPCION  )
    VALUES (PTIPO ,PDESCRIPCION);
    EXCEPTION WHEN OTHERS THEN ROLLBACK;
    
END SP_TP_CUOTA;
COMMIT;


CREATE OR REPLACE PROCEDURE SP_DEL_TP_CUOTA(PTIPO IN VARCHAR2)
IS
BEGIN
    DELETE FROM CONDOMINIO.TIPO_CUOTAS  WHERE TIPO = PTIPO ;
    EXCEPTION WHEN OTHERS THEN ROLLBACK;
    
END SP_DEL_TP_CUOTA;
COMMIT;


CREATE OR REPLACE PROCEDURE SP_UPD_TP_CUOTA(PTIPO IN VARCHAR2,PDESCRIPCION IN VARCHAR2)
IS
BEGIN
    UPDATE  CONDOMINIO.TIPO_CUOTAS SET  DESCRIPCION = PDESCRIPCION WHERE TIPO = PTIPO;
    EXCEPTION WHEN OTHERS THEN ROLLBACK;
    
END  SP_UPD_TP_CUOTA;
COMMIT;


--------------------------------CUOTAS----------------------------------------

create or replace NONEDITIONABLE PROCEDURE SP_CUOTAS(PID_COUTA IN INT ,PNUM_CASA IN INT ,PPRECIO IN FLOAT ,PTIPO IN VARCHAR2)
IS
BEGIN
    INSERT INTO CONDOMINIO.CUOTAS_CONDOMINALES(ID_COUTA ,NUM_CASA ,PRECIO  ,TIPO)
    VALUES (PID_COUTA ,PNUM_CASA ,PPRECIO  ,PTIPO);
    EXCEPTION WHEN OTHERS THEN ROLLBACK;
    
END SP_CUOTAS;
COMMIT;



CREATE OR REPLACE PROCEDURE SP_DEL_CUOTAS(PID_COUTA IN INT)
IS
BEGIN
    DELETE FROM CONDOMINIO.CUOTAS_CONDOMINALES WHERE ID_COUTA = PID_COUTA;
    EXCEPTION WHEN OTHERS THEN ROLLBACK;
   
END SP_DEL_CUOTAS;
COMMIT;


CREATE OR REPLACE PROCEDURE SP_UPD_CUOTAS( PID_COUTA IN INT ,PNUM_CASA IN INT ,PPRECIO IN FLOAT ,PTIPO IN VARCHAR2)
IS
BEGIN
    UPDATE  CONDOMINIO.CUOTAS_CONDOMINALES SET NUM_CASA = PNUM_CASA, PRECIO = PPRECIO , TIPO = PTIPO WHERE ID_COUTA = PID_COUTA;
    EXCEPTION WHEN OTHERS THEN ROLLBACK;
   
END SP_UPD_CUOTAS;
COMMIT;


--------------------------------ACCESOS----------------------------------------



create or replace NONEDITIONABLE PROCEDURE SP_ACESSOS(PCEDULA IN VARCHAR2 ,PNOMBRE IN VARCHAR2 ,PAPE1 IN VARCHAR2 ,PAPE2 IN VARCHAR2,PNUM_CASA IN INT ,PDESCRIPCION IN VARCHAR2,PFECHA IN VARCHAR2)
IS
BEGIN
    INSERT INTO CONDOMINIO.ACCESOS(CEDULA ,NOMBRE  ,APE1 ,APE2 ,NUM_CASA ,DESCRIPCION ,FECHA )
    VALUES (PCEDULA ,PNOMBRE  ,PAPE1 ,PAPE2 ,PNUM_CASA ,PDESCRIPCION ,PFECHA );
    
    EXCEPTION WHEN OTHERS THEN ROLLBACK;
END SP_ACESSOS;
COMMIT;


CREATE OR REPLACE PROCEDURE SP_DEL_ACESSOS(PCEDULA IN VARCHAR2)
IS
BEGIN
    DELETE FROM CONDOMINIO.ACCESOS WHERE CEDULA = PCEDULA ;
    
    EXCEPTION WHEN OTHERS THEN ROLLBACK;
END SP_DEL_ACESSOS;
COMMIT;


CREATE OR REPLACE PROCEDURE SP_UPD_ACESSOS(PCEDULA IN VARCHAR2 ,PNOMBRE IN VARCHAR2 ,PAPE1 IN VARCHAR2 ,PAPE2 IN VARCHAR2,PNUM_CASA IN INT ,PDESCRIPCION IN VARCHAR2,PFECHA IN VARCHAR2)
IS
BEGIN
    UPDATE  CONDOMINIO.ACCESOS SET NOMBRE = PNOMBRE, APE1 = PAPE1, APE2 = PAPE2, NUM_CASA = PNUM_CASA, DESCRIPCION = PDESCRIPCION, FECHA = PFECHA WHERE CEDULA = PCEDULA;
    
    EXCEPTION WHEN OTHERS THEN ROLLBACK;
    
END SP_UPD_ACESSOS;
COMMIT;


--------------------------------TRIGGER----------------------------------------


CREATE OR REPLACE TRIGGER TR_DUENO_FILIARES
AFTER INSERT ON CONDOMINIO.DUENOS
FOR EACH ROW
BEGIN
    INSERT INTO CONDOMINIO.FILIARES_CONDOMINIOS(NUM_CASA , CEDULA_DUENO)
    VALUES(SQ_NUMCASA.NEXTVAL,:NEW.CEDULA);
END TR_DUENO_FILIARES;

ALTER TRIGGER TR_DUENO_FILIARES DISABLE; 
ALTER TRIGGER TR_DUENO_FILIARES ENABLE;




COMMIT;


---------------------------------------------------------------------------------------------&----------------------------------------------------------------------
--CURSOR
--
set serveroutput on;
CREATE OR REPLACE PROCEDURE SP_cursor
IS
begin
declare
  v_NUM_CASANivel1 NUMBER;
  v_CEDULA_DUENONivel1 varchar2(50);
  v_ID_COUTANivel2 NUMBER;
  v_NUM_CASANivel2 NUMBER;
  v_PRECIONivel2 NUMBER;
  v_TIPONivel2 varchar2(50);
  
  
  cursor cur_nivel1 is
    select NUM_CASA,CEDULA_DUENO from CONDOMINIO.FILIARES_CONDOMINIOS order by 1;
 cursor cur_nivel2 is
      select ID_COUTA, NUM_CASA, PRECIO, TIPO from CONDOMINIO.CUOTAS_CONDOMINALES 
      where to_char(SUBSTR(NUM_CASA,1,100)) = trim(v_NUM_CASANivel1);     
begin   
   open cur_nivel1;
   loop
      fetch cur_nivel1 into v_NUM_CASANivel1, v_CEDULA_DUENONivel1;
      EXIT WHEN cur_nivel1%NOTFOUND;
      DBMS_OUTPUT.PUT_LINE( '----------------------' );
        DBMS_OUTPUT.PUT_LINE('NUMERO DE CASA : ' ||  to_char(v_NUM_CASANivel1) || ' | ' || 'CEDULA DEL DUEÑO : ' ||  to_char(v_CEDULA_DUENONivel1));
        
  open cur_nivel2;
  loop
      fetch cur_nivel2 into v_ID_COUTANivel2, v_NUM_CASANivel2, v_PRECIONivel2, v_TIPONivel2;
      EXIT WHEN cur_nivel2%NOTFOUND;
      DBMS_OUTPUT.PUT_LINE(' ID DE LA COUTA : ' || to_char(v_ID_COUTANivel2) || ' | ' || ' NUMERO DE CASA : ' || to_char(v_NUM_CASANivel2) || ' | ' || ' PRECIO : ' || to_char(v_PRECIONivel2)||' | ' || 'TIPO : ' || to_char(v_TIPONivel2) );
        end loop;
    close cur_nivel2;
   end loop;
   close cur_nivel1;
   end;
END SP_cursor;

set serveroutput on;
EXECUTE SP_cursor; 

COMMIT;
 








